fieldLayouts:
  bec19259-136b-4808-a6f3-494080fde62f:
    tabs:
      -
        elements:
          -
            fieldUid: be6d086f-56a5-46be-9805-16a1b0d9db3a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: siteInfo
name: 'Site Info'
