fieldLayouts:
  bec19259-136b-4808-a6f3-494080fde62f:
    tabs:
      -
        elements:
          -
            fieldUid: f994d628-0ddd-4611-972c-f6279e16cbf8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bcd7b15f-d259-40b1-b91e-7d4dd34dd31d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 98e2edbd-acba-4a11-b710-0b20640153d7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 32b2ad79-e016-4d1a-825e-64775b6673b7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f504dfe-5429-45d1-85a5-9ea127080883
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: siteInfo
name: 'Site Info'
