enableVersioning: true
handle: article
name: Articulo
propagationMethod: all
siteSettings:
  97f57858-b416-4aac-877d-78bebb1bdbe6:
    enabledByDefault: true
    hasUrls: true
    template: templates/article
    uriFormat: article
type: single
