enableVersioning: true
handle: contact
name: Contacto
propagationMethod: all
siteSettings:
  97f57858-b416-4aac-877d-78bebb1bdbe6:
    enabledByDefault: true
    hasUrls: true
    template: templates/contact
    uriFormat: contacto
type: single
