field: bcd7b15f-d259-40b1-b91e-7d4dd34dd31d
fieldLayouts:
  54c33367-46e4-4a51-b192-4096f5a1c5c2:
    tabs:
      -
        elements:
          -
            fieldUid: 3134121c-a5c6-4588-9b66-7aa5a866e077
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 8bd28df4-c540-4ea6-b68a-3950dbb0f226
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3134121c-a5c6-4588-9b66-7aa5a866e077:
    contentColumnType: string(255)
    fieldGroup: null
    handle: menuItemLink
    instructions: ''
    name: 'Menu Item Link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  8bd28df4-c540-4ea6-b68a-3950dbb0f226:
    contentColumnType: text
    fieldGroup: null
    handle: menuItemName
    instructions: ''
    name: 'Menu Item Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: menuElements
name: 'Menu Elements'
sortOrder: 1
