contentColumnType: text
fieldGroup: 89e96ba2-3a8a-4bd6-91c6-1e2d58d07def
handle: footer
instructions: ''
name: 'Créditos del footer'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
